apiVersion: v1
kind: ConfigMap
metadata:
  name: kolab-test-env
data:
  APP_DEBUG: "true"
  APP_DOMAIN: kolab.local
  APP_ENV: local
  APP_HEADER_CSP: '"connect-src ''self''; child-src ''self''; font-src ''self''; form-action
    ''self'' data:; frame-ancestors ''self''; img-src blob: data: ''self'' *; media-src
    ''self''; object-src ''self''; script-src ''self'' ''unsafe-inline'' ''unsafe-eval'';
    style-src ''self'' ''unsafe-eval'' ''unsafe-inline''; default-src ''self'';"'
  APP_HEADER_XFO: sameorigin
  APP_IMAP: "1"
  APP_KEY: base64:EFXja/fHF01EMKiXW200b5zWOynbPzAHfUM78bOp+28=
  APP_LDAP: "0"
  APP_LOCALE: en
  APP_LOCALES: ""
  APP_NAME: Kolab
  APP_PASSPHRASE: simple123
  APP_PUBLIC_URL: https://kolab.local
  APP_TENANT_ID: "5"
  APP_THEME: default
  APP_URL: https://kolab.local
  APP_WEBSITE_DOMAIN: kolab.local
  APP_WITH_ADMIN: "1"
  APP_WITH_FILES: "1"
  APP_WITH_RESELLER: "1"
  APP_WITH_SERVICES: "1"
  APP_WITH_SIGNUP: "1"
  APP_WITH_WALLET: "1"
  ASSET_URL: https://kolab.local
  BROADCAST_DRIVER: redis
  CACHE_DRIVER: redis
  COMPANY_ADDRESS: ""
  COMPANY_DETAILS: ""
  COMPANY_EMAIL: ""
  COMPANY_FOOTER: ""
  COMPANY_LOGO: ""
  COMPANY_NAME: kolab.org
  DB_CONNECTION: mysql
  DB_DATABASE: kolabdev
  DB_HOST: mariadb
  DB_PASSWORD: simple123
  DB_PORT: "3306"
  DB_ROOT_PASSWORD: simple123
  DB_USERNAME: kolabdev
  DES_KEY: kBxUM/53N9p9abusAoT0ZEAxwI2pxFz/
  DNS_COPY_FROM: "null"
  DNS_SPF: '"v=spf1 mx -all"'
  DNS_STATIC: '"%s.    MX  10 ext-mx01.mykolab.com."'
  DNS_TTL: "3600"
  FILESYSTEM_DISK: minio
  FIREBASE_API_KEY: ""
  GIT_REF_AUTOCONF: master
  GIT_REF_CHWALA: dev/mollekopf
  GIT_REF_FREEBUSY: master
  GIT_REF_IRONY: master
  GIT_REF_ROUNDCUBEMAIL: dev/kolab-1.5
  GIT_REF_ROUNDCUBEMAIL_PLUGINS: master
  GIT_REF_SYNCROTON: master
  GIT_REMOTE_AUTOCONF: https://git.kolab.org/diffusion/AC/autoconf.git
  GIT_REMOTE_CHWALA: https://git.kolab.org/diffusion/C/chwala.git
  GIT_REMOTE_FREEBUSY: https://git.kolab.org/diffusion/F/freebusy.git
  GIT_REMOTE_IRONY: https://git.kolab.org/source/iRony.git
  GIT_REMOTE_ROUNDCUBEMAIL: https://git.kolab.org/source/roundcubemail.git
  GIT_REMOTE_ROUNDCUBEMAIL_PLUGINS: https://git.kolab.org/diffusion/RPK/roundcubemail-plugins-kolab.git
  GIT_REMOTE_SYNCROTON: https://git.kolab.org/diffusion/S/syncroton.git
  IMAP_ADMIN_LOGIN: cyrus-admin
  IMAP_ADMIN_PASSWORD: simple123
  IMAP_GIT_REF: dev/mollekopf
  IMAP_GIT_REMOTE: https://git.kolab.org/source/cyrus-imapd
  IMAP_GUAM_PORT: "11143"
  IMAP_HOST: imap
  IMAP_PORT: "11143"
  IMAP_URI: localhost:11143
  IMAP_VERIFY_HOST: "false"
  IMAP_VERIFY_PEER: "false"
  IMAP_WITH_GROUPWARE_DEFAULT_FOLDERS: "false"
  KB_ACCOUNT_DELETE: ""
  KB_ACCOUNT_SUSPENDED: ""
  KB_PAYMENT_SYSTEM: ""
  KOLAB_GIT_REF: dev/mollekopf
  KOLAB_GIT_REMOTE: https://git.kolab.org/source/kolab
  KOLAB_SSL_CERTIFICATE: /etc/certs/kolab.hosted.com.cert
  KOLAB_SSL_CERTIFICATE_FULLCHAIN: /etc/certs/kolab.hosted.com.chain.pem
  KOLAB_SSL_CERTIFICATE_KEY: /etc/certs/kolab.hosted.com.key
  LOG_CHANNEL: stdout
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug
  LOG_SLOW_REQUESTS: "5"
  MAIL_ENCRYPTION: starttls
  MAIL_FROM_ADDRESS: '"noreply@kolab.local"'
  MAIL_FROM_NAME: '"kolab.local"'
  MAIL_HOST: localhost
  MAIL_MAILER: smtp
  MAIL_PASSWORD: '"simple123"'
  MAIL_PORT: "587"
  MAIL_REPLYTO_ADDRESS: '"noreply@kolab.local"'
  MAIL_REPLYTO_NAME: "null"
  MAIL_USERNAME: '"noreply@kolab.local"'
  MAIL_VERIFY_PEER: '''false'''
  MEET_LISTENING_HOST: meet
  MEET_PUBLIC_DOMAIN: kolab.local
  MEET_SERVER_TOKEN: simple123
  MEET_SERVER_URLS: https://127.0.0.1:6443/meetmedia/api/
  MEET_SERVER_VERIFY_TLS: "false"
  MEET_WEBHOOK_TOKEN: simple123
  MEET_WEBRTC_LISTEN_IP: '''127.0.0.1'''
  MFA_DSN: mysql://roundcube:simple123@mariadb/roundcube
  MFA_TOTP_DIGEST: sha1
  MFA_TOTP_DIGITS: "6"
  MFA_TOTP_INTERVAL: "30"
  MINIO_BUCKET: kolab
  MINIO_ENDPOINT: http://minio:9000
  MINIO_PASSWORD: simple123
  MINIO_USER: minio
  MIX_ASSET_PATH: '''/'''
  MOLLIE_KEY: ""
  OCTANE_HTTP_HOST: kolab.local
  OPENEXCHANGERATES_API_KEY: ""
  PASSPORT_PROXY_OAUTH_CLIENT_ID: 5909ca4f-df7e-45fe-b355-e7c195aef117
  PASSPORT_PROXY_OAUTH_CLIENT_SECRET: 3URb+3JGJM9wPuDnlUSTPOw2mqmHsoOV8NXanx9xwQM=
  PASSWORD_POLICY: ""
  PGP_AGENT: /usr/bin/gpg-agent
  PGP_BINARY: /usr/bin/gpg
  PGP_ENABLE: "true"
  PGP_GPGCONF: /usr/bin/gpgconf
  PGP_LENGTH: ""
  PROXY_SSL_CERTIFICATE: /etc/certs/imap.hosted.com.cert
  PROXY_SSL_CERTIFICATE_KEY: /etc/certs/imap.hosted.com.key
  QUEUE_CONNECTION: redis
  RATELIMIT_WHITELIST: '"noreply@kolab.local"'
  REDIS_HOST: redis
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
  SMTP_HOST: imap
  SMTP_PORT: "10587"
  STRIPE_KEY: ""
  STRIPE_PUBLIC_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
  SUPPORT_URL: /support
  SWOOLE_PACKAGE_MAX_LENGTH: "10485760"
  TRUSTED_PROXIES: '"172.18.0.7/8,127.0.0.1/8"'
  VAT_COUNTRIES: CH,LI
  VAT_RATE: "7.7"
  WEBMAIL_URL: /roundcubemail/
